### ISSUE TITLE
Application stays in task manager

### ISSUE THREAD

**Issue by Marcos-AV** [JulyIghor/TurnOffXboxController#1]
After turning off all the controllers, the application still stays in task manager, using around 1,2MB of memory.

A new instance doesn't kill the previous one, so the instances will pile up in the task manager. Please check: https://imgur.com/niDBJtl

The application is great, but is there anything to prevent it from staying in task manager?

**Comment by JulyIghor** [comment]
There is no code inside of app that could do freeze or waiting, it just calls function in xbox driver dll file max 4 times and then exit.
Possible that third party app could cause this issue, maybe antivirus is sniffing dll calls and it stuck.
Maybe 64 bit build or just compilation with latest compiler would help, but I have no xbox 360 controller any more, so I can't try myself.
If you don't solve it I can try to compile it on latest compiler and send you update for test.

**Comment by Marcos-AV** [comment]
I'll be waiting for you to compile and send me the new binaries, then. Thanks.

**Comment by JulyIghor** [comment]
Just to be sure I understand. App doing its job and controllers off, but won't exit itself?

**Comment by JulyIghor** [comment]
And please verify MD5 hash for exe file you have d9a0ef2c757a29b8677f42aa5eefd087
Is it correct?

**Comment by Marcos-AV** [comment]
That's correct!

**Comment by stevvie** [comment]
Same for me, run the app it turns off my Xbox 360 controller ok but stays resident. If i then turn on the controller and run the app again i get ANOTHER version left in task manager.

**Comment by JulyIghor** [comment]
This was not something that I could fix nicely.
Microsoft won't update XInput1_3.dll file that is part of driver.
And there is some threads that being stuck on Windows 10 and won't let process to shut down correctly.
So I have added code that kills app and preventing this.
Please test it and it something wrong open issue again.

https://github.com/JulyIghor/TurnOffXboxController/releases
